"""init

Revision ID: d3387d92698b
Revises: 
Create Date: 2022-03-15 09:16:23.624813

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision = 'd3387d92698b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pub_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('headline', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('main_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_article_headline'), 'article', ['headline'], unique=False)
    op.create_index(op.f('ix_article_id'), 'article', ['id'], unique=False)
    op.create_index(op.f('ix_article_main_text'), 'article', ['main_text'], unique=False)
    op.create_index(op.f('ix_article_notes'), 'article', ['notes'], unique=False)
    op.create_index(op.f('ix_article_pub_date'), 'article', ['pub_date'], unique=False)
    op.create_index(op.f('ix_article_url'), 'article', ['url'], unique=False)
    op.create_table('disease',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disease_id'), 'disease', ['id'], unique=False)
    op.create_index(op.f('ix_disease_name'), 'disease', ['name'], unique=False)
    op.create_table('location',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('region', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('longitude', sa.Numeric(), nullable=True),
    sa.Column('latitude', sa.Numeric(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_city'), 'location', ['city'], unique=False)
    op.create_index(op.f('ix_location_country'), 'location', ['country'], unique=False)
    op.create_index(op.f('ix_location_id'), 'location', ['id'], unique=False)
    op.create_index(op.f('ix_location_latitude'), 'location', ['latitude'], unique=False)
    op.create_index(op.f('ix_location_longitude'), 'location', ['longitude'], unique=False)
    op.create_index(op.f('ix_location_name'), 'location', ['name'], unique=False)
    op.create_index(op.f('ix_location_region'), 'location', ['region'], unique=False)
    op.create_table('syndrome',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syndrome_id'), 'syndrome', ['id'], unique=False)
    op.create_index(op.f('ix_syndrome_name'), 'syndrome', ['name'], unique=False)
    op.create_table('report',
    sa.Column('event_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('disease_id', sa.Integer(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=True),
    sa.Column('article_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['disease_id'], ['disease.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_article_id'), 'report', ['article_id'], unique=False)
    op.create_index(op.f('ix_report_disease_id'), 'report', ['disease_id'], unique=False)
    op.create_index(op.f('ix_report_event_date'), 'report', ['event_date'], unique=False)
    op.create_index(op.f('ix_report_id'), 'report', ['id'], unique=False)
    op.create_index(op.f('ix_report_location_id'), 'report', ['location_id'], unique=False)
    op.create_index(op.f('ix_report_notes'), 'report', ['notes'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_notes'), table_name='report')
    op.drop_index(op.f('ix_report_location_id'), table_name='report')
    op.drop_index(op.f('ix_report_id'), table_name='report')
    op.drop_index(op.f('ix_report_event_date'), table_name='report')
    op.drop_index(op.f('ix_report_disease_id'), table_name='report')
    op.drop_index(op.f('ix_report_article_id'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_syndrome_name'), table_name='syndrome')
    op.drop_index(op.f('ix_syndrome_id'), table_name='syndrome')
    op.drop_table('syndrome')
    op.drop_index(op.f('ix_location_region'), table_name='location')
    op.drop_index(op.f('ix_location_name'), table_name='location')
    op.drop_index(op.f('ix_location_longitude'), table_name='location')
    op.drop_index(op.f('ix_location_latitude'), table_name='location')
    op.drop_index(op.f('ix_location_id'), table_name='location')
    op.drop_index(op.f('ix_location_country'), table_name='location')
    op.drop_index(op.f('ix_location_city'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_disease_name'), table_name='disease')
    op.drop_index(op.f('ix_disease_id'), table_name='disease')
    op.drop_table('disease')
    op.drop_index(op.f('ix_article_url'), table_name='article')
    op.drop_index(op.f('ix_article_pub_date'), table_name='article')
    op.drop_index(op.f('ix_article_notes'), table_name='article')
    op.drop_index(op.f('ix_article_main_text'), table_name='article')
    op.drop_index(op.f('ix_article_id'), table_name='article')
    op.drop_index(op.f('ix_article_headline'), table_name='article')
    op.drop_table('article')
    # ### end Alembic commands ###
